sudo: required
services:
  - docker

before_install:
  - docker build -t naregb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true naregb/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-835746095792"
  bucker_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"